### ISSUE TITLE
Debug configuration does not build successfully.

### ISSUE THREAD

**Issue by XenHat** [telegramdesktop/opus#1]
The current Telegram (for Desktop) build directives instructs readers to build both Debug and Release configurations of the Opus library. I do not know if this is an oversight or not, but the Debug configuration does not build for multiple reasons:

```
// m.cpp
int a() {
// I'm pretty sure this goes against several cpp rules.
// This generates C4716
}
```

Upon adding a generic "return 0;", another error crops up:
`error LNK1561: entry point must be defined                | Project: m`

The release configuration builds fine, however, and the directives makes me believe that only Release is required.

**Comment by john-preston** [comment]
It should work now :D
